import { promises as fs } from "node:fs";import path from "node:path";
export type MemoryKind="fact"|"preference"|"goal"|"decision"|"project"|"context"|"instruction";
export type AdvancedMemory={id:string;sessionId:string;kind:MemoryKind;content:string;importance:number;source:"user"|"assistant"|"system";createdAt:number;updatedAt:number;lastUsedAt?:number;tags:string[]};
const file=path.resolve(process.env.DATA_DIR||"data","advanced-memory.json"),store=new Map<string,AdvancedMemory[]>();let loaded=false;
async function load(){if(loaded)return;loaded=true;try{const obj=JSON.parse(await fs.readFile(file,"utf8"));for(const[k,v]of Object.entries(obj))if(Array.isArray(v))store.set(k,v as AdvancedMemory[])}catch{}}
async function persist(){await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify(Object.fromEntries(store),null,2),"utf8")}
export async function saveAdvancedMemory(sessionId:string,input:Omit<AdvancedMemory,"id"|"sessionId"|"createdAt"|"updatedAt">){await load();const list=store.get(sessionId)||[],now=Date.now(),normalized=input.content.trim().toLowerCase(),existing=list.find(x=>x.kind===input.kind&&x.content.trim().toLowerCase()===normalized);if(existing){Object.assign(existing,input,{updatedAt:now,lastUsedAt:now});await persist();return existing}const item={...input,id:crypto.randomUUID(),sessionId,createdAt:now,updatedAt:now};list.push(item);store.set(sessionId,list.slice(-500));await persist();return item}
export async function searchAdvancedMemory(sessionId:string,query:string,limit=12){await load();const terms=query.toLowerCase().split(/\s+/).filter(x=>x.length>2),list=store.get(sessionId)||[];return list.map(x=>{const text=(x.content+" "+x.tags.join(" ")).toLowerCase(),score=terms.reduce((n,t)=>n+(text.includes(t)?1:0),0)+x.importance*.1;return{x,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>{x.x.lastUsedAt=Date.now();return x.x})}
export async function getAdvancedMemories(sessionId:string,kind?:MemoryKind){await load();return(store.get(sessionId)||[]).filter(x=>!kind||x.kind===kind).sort((a,b)=>b.importance-a.importance||b.updatedAt-a.updatedAt)}
export async function deleteAdvancedMemory(sessionId:string,id:string){await load();const list=store.get(sessionId)||[];store.set(sessionId,list.filter(x=>x.id!==id));await persist()}
export async function clearAdvancedMemory(sessionId:string){await load();store.delete(sessionId);await persist()}
export function memoryKinds():MemoryKind[]{return["fact","preference","goal","decision","project","context","instruction"]}
