import { spawn } from "node:child_process";import { promises as fs } from "node:fs";import path from "node:path";import os from "node:os";
export type ComputerResult={success:boolean;data?:unknown;error?:string;durationMs?:number};
const started=()=>Date.now();
export function computerInfo(){return{platform:process.platform,arch:process.arch,node:process.version,hostname:os.hostname(),home:os.homedir(),cwd:process.cwd(),user:os.userInfo().username,temp:os.tmpdir(),cpus:os.cpus().length,memory:{total:os.totalmem(),free:os.freemem()}}}
function resolve(input:string){return path.resolve(input||process.cwd())}
export async function listPath(input:string):Promise<ComputerResult>{const t=started();try{const target=resolve(input);const entries=await fs.readdir(target,{withFileTypes:true});return{success:true,data:{path:target,entries:entries.map(e=>({name:e.name,type:e.isDirectory()?"directory":e.isSymbolicLink()?"symlink":"file"})).sort((a,b)=>a.type.localeCompare(b.type)||a.name.localeCompare(b.name))},durationMs:Date.now()-t}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao listar caminho",durationMs:Date.now()-t}}}
export async function readFile(input:string):Promise<ComputerResult>{const t=started();try{const target=resolve(input);const stat=await fs.stat(target);if(!stat.isFile())return{success:false,error:"O caminho não é um arquivo."};if(stat.size>10*1024*1024)return{success:false,error:"Arquivo excede o limite de leitura de 10 MB."};const content=await fs.readFile(target,"utf8");return{success:true,data:{path:target,size:stat.size,content},durationMs:Date.now()-t}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao ler arquivo",durationMs:Date.now()-t}}}
export async function writeFile(input:string,content:string):Promise<ComputerResult>{const t=started();try{const target=resolve(input);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,content,"utf8");return{success:true,data:{path:target,bytes:Buffer.byteLength(content,"utf8")},durationMs:Date.now()-t}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao escrever arquivo",durationMs:Date.now()-t}}}
export async function deletePath(input:string):Promise<ComputerResult>{const t=started();try{const target=resolve(input);await fs.rm(target,{recursive:true,force:false});return{success:true,data:{path:target,deleted:true},durationMs:Date.now()-t}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao excluir caminho",durationMs:Date.now()-t}}}
export async function movePath(from:string,to:string):Promise<ComputerResult>{const t=started();try{const source=resolve(from),target=resolve(to);await fs.mkdir(path.dirname(target),{recursive:true});await fs.rename(source,target);return{success:true,data:{from:source,to:target},durationMs:Date.now()-t}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao mover caminho",durationMs:Date.now()-t}}}
export async function runCommand(command:string,cwd?:string,timeoutMs=60000):Promise<ComputerResult>{const t=started();if(!command.trim())return{success:false,error:"Comando vazio."};return new Promise(resolvePromise=>{const isWin=process.platform==="win32",shell=isWin?(process.env.ComSpec||"cmd.exe"):process.env.SHELL||"/bin/sh";const args=isWin?["/d","/s","/c",command],["-lc",command];const child=spawn(shell,args,{cwd:cwd?resolve(cwd):process.cwd(),env:process.env,windowsHide:true,stdio:["ignore","pipe","pipe"]});let stdout="",stderr="",settled=false;const finish=(result:ComputerResult)=>{if(settled)return;settled=true;resolvePromise({...result,durationMs:Date.now()-t})};const timer=setTimeout(()=>{child.kill("SIGTERM");finish({success:false,error:"TIMEOUT",data:{stdout,stderr}})},timeoutMs);child.stdout.on("data",d=>{stdout+=d.toString();if(stdout.length>2_000_000)stdout=stdout.slice(-2_000_000)});child.stderr.on("data",d=>{stderr+=d.toString();if(stderr.length>2_000_000)stderr=stderr.slice(-2_000_000)});child.on("error",e=>{clearTimeout(timer);finish({success:false,error:e.message,data:{stdout,stderr}})});child.on("close",code=>{clearTimeout(timer);finish({success:code===0,data:{code,stdout,stderr,cwd:cwd?resolve(cwd):process.cwd() },error:code===0?undefined:`Processo terminou com código ${code}`})})})}
