import { promises as fs } from "node:fs";
import path from "node:path";
import { callModel } from "./ai";
import { detectTestCommand,runProjectCommand,writeProjectFile } from "./development-agent";
import { parseDiagnostics,Diagnostic } from "./development-loop";

type Patch={file:string;content:string;reason?:string};
export type AutofixResult={success:boolean;iterations:number;changes:Patch[];diagnostics:Diagnostic[];history:any[];error?:string};
const ignored=new Set(["node_modules","dist","build",".git","coverage"]);
const sourceExt=/\.(ts|tsx|js|jsx|mjs|cjs|json|css|html|py|java|go|rs|cs)$/i;
async function collect(root:string,maxFiles=18,maxChars=90000){const out:Array<{file:string;content:string}>=[];async function walk(dir:string){if(out.length>=maxFiles)return;for(const entry of await fs.readdir(dir,{withFileTypes:true})){if(out.length>=maxFiles)break;if(ignored.has(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())await walk(full);else if(entry.isFile()&&sourceExt.test(entry.name)){const stat=await fs.stat(full);if(stat.size<=250000){const content=await fs.readFile(full,"utf8");if(content.length<maxChars)out.push({file:path.relative(root,full),content})}}}}await walk(root);return out}
function parseJson(raw:string){try{return JSON.parse(raw)}catch{const m=raw.match(/```(?:json)?\s*([\s\S]*?)```/i);if(m)try{return JSON.parse(m[1])}catch{}const a=raw.indexOf("{");const b=raw.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(raw.slice(a,b+1))}catch{}return null}}
async function propose(root:string,objective:string,diagnostics:Diagnostic[],files:Array<{file:string;content:string}>):Promise<Patch[]>{const prompt=`Você é o engenheiro de software da A.R.I.S. Corrija um projeto real. Analise apenas os arquivos fornecidos e os diagnósticos. Retorne SOMENTE JSON válido no formato {"patches":[{"file":"caminho","content":"conteúdo COMPLETO do arquivo","reason":"motivo"}]}. Não invente arquivos nem APIs. Preserve comportamento não relacionado ao erro. Não inclua markdown. Objetivo: ${objective}\nDIAGNÓSTICOS:\n${JSON.stringify(diagnostics)}\nARQUIVOS:\n${files.map(f=>`\n--- ${f.file} ---\n${f.content}`).join("\n")}`;const raw=await callModel("A.R.I.S. DEVELOPMENT AUTOFIX ENGINE. Gere correções pequenas, determinísticas e compiláveis.",[ {role:"user",content:prompt} ]);if(raw.startsWith("IA configurável:"))throw new Error(raw);const parsed=parseJson(raw);if(!parsed||!Array.isArray(parsed.patches))throw new Error("O modelo não retornou patches válidos.");return parsed.patches.filter((p:any)=>p&&typeof p.file==="string"&&typeof p.content==="string").slice(0,5)}
export async function autofixProject(root:string,objective:string,command?:string,maxIterations=3):Promise<AutofixResult>{const history:any[]=[];const changes:Patch[]=[];let diagnostics:Diagnostic[]=[];const max=Math.max(1,Math.min(4,maxIterations||3));const detected=await detectTestCommand(root);const run=command||(detected.data as any)?.recommendedCommand;if(!run)return{success:false,iterations:0,changes,diagnostics,history,error:"Nenhum comando de teste/build foi identificado."};for(let i=1;i<=max;i++){const result=await runProjectCommand(root,run,120000);const raw=String((result.data as any)?.stdout??(result.data as any)?.stderr??result.error??"");const parsed=parseDiagnostics(raw);diagnostics=parsed;history.push({iteration:i,step:"verify",success:result.success,diagnostics:parsed,output:result.data,error:result.error});if(result.success)return{success:true,iterations:i,changes,diagnostics,history};const files=await collect(path.resolve(root));const patches=await propose(path.resolve(root),objective,parsed,files);if(!patches.length)return{success:false,iterations:i,changes,diagnostics,history,error:"Não foi possível determinar uma correção segura."};for(const patch of patches){const written=await writeProjectFile(root,patch.file,patch.content);if(!written.success)return{success:false,iterations:i,changes,diagnostics,history,error:written.error||"Falha ao aplicar patch"};changes.push(patch);history.push({iteration:i,step:"apply-patch",file:patch.file,reason:patch.reason})}}return{success:false,iterations:max,changes,diagnostics,history,error:"Limite de tentativas atingido; o projeto ainda apresenta falhas."}}
