import { inspectProject,detectTestCommand,runProjectCommand,readProjectFile } from "./development-agent";
export type Diagnostic={message:string;file?:string;line?:number;column?:number;kind:"typescript"|"eslint"|"test"|"build"|"runtime"|"unknown"};
export type LoopResult={success:boolean;iterations:number;history:Array<{step:string;success:boolean;output?:unknown;error?:string}>;diagnostics:Diagnostic[];final?:unknown;nextAction?:string};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const limit=(n:number)=>Math.max(1,Math.min(5,n||3));
function textOf(x:any){return String(x?.data?.stdout??x?.data?.stderr??x?.error??x?.data?.output??"")}
export function parseDiagnostics(raw:string):Diagnostic[]{const out:Diagnostic[]=[];const lines=raw.split(/\r?\n/);for(const line of lines){let m=line.match(/(.+?)\((\d+),(\d+)\):\s*(?:error|warning)?\s*(.+)/i);if(m){out.push({file:m[1].trim(),line:Number(m[2]),column:Number(m[3]),message:m[4].trim(),kind:/TS\d+|typescript/i.test(line)?"typescript":"unknown"});continue}m=line.match(/(.+?):(\d+):(\d+)\s*-?\s*(?:error|warning)?\s*(.+)/i);if(m){out.push({file:m[1].trim(),line:Number(m[2]),column:Number(m[3]),message:m[4].trim(),kind:/eslint/i.test(line)?"eslint":"unknown"});continue}if(/FAIL|failed|error|exception|syntaxerror|typeerror/i.test(line)&&line.trim())out.push({message:line.trim(),kind:/test|fail/i.test(line)?"test":/build/i.test(line)?"build":"runtime"})}return out.slice(0,30)}
function candidateFiles(diags:Diagnostic[]){return [...new Set(diags.map(d=>d.file).filter(Boolean))].slice(0,20)}
export async function runDevelopmentLoop(root:string,command?:string,maxIterations=3):Promise<LoopResult>{const history:any[]=[];const diagnostics:Diagnostic[]=[];const max=limit(maxIterations);const inspect=await inspectProject(root);history.push({step:"inspect",success:inspect.success,output:inspect.data,error:inspect.error});if(!inspect.success)return{success:false,iterations:0,history,diagnostics,nextAction:"Corrigir o caminho do projeto antes de continuar."};const detected=await detectTestCommand(root);history.push({step:"detect-tests",success:detected.success,output:detected.data,error:detected.error});const run=command||(detected.data as any)?.recommendedCommand;if(!run)return{success:true,iterations:0,history,diagnostics,final:{message:"Nenhum comando automático de teste/build foi identificado."}};for(let i=1;i<=max;i++){const result=await runProjectCommand(root,run,120000);const raw=textOf(result);const parsed=parseDiagnostics(raw);diagnostics.push(...parsed.filter(d=>!diagnostics.some(x=>x.file===d.file&&x.line===d.line&&x.message===d.message)));history.push({step:`run-${i}`,success:result.success,output:result.data,error:result.error,diagnostics:parsed});if(result.success)return{success:true,iterations:i,history,diagnostics,final:result.data,nextAction:"Verificar alterações e entregar o projeto."};if(i<max){const files=candidateFiles(parsed);if(files.length){history.push({step:`diagnostic-${i}`,success:true,output:{candidateFiles:files,diagnostics:parsed}})}await sleep(150)}else{return{success:false,iterations:i,history,diagnostics,final:{message:"O projeto continua falhando após as tentativas permitidas."},nextAction:"Analisar os diagnósticos, editar os arquivos candidatos e executar novamente."}}}return{success:false,iterations:max,history,diagnostics,nextAction:"Analisar diagnósticos e corrigir o projeto."}}
export async function diagnoseProjectError(root:string,file?:string){if(!file)return{success:true,data:{message:"Forneça o arquivo suspeito para análise localizada.",hint:"Use os diagnostics retornados por dev_verify_project para localizar arquivos e linhas."}};return readProjectFile(root,file)}
