import { promises as fs } from "node:fs";
import path from "node:path";
import { runCommand } from "./computer-core";

export type DevResult={success:boolean;data?:unknown;error?:string};
const safeRoot=(root:string)=>path.resolve(root||process.cwd());
const blocked=/\b(rm\s+-rf|format\s+[a-z]:|del\s+\/s|shutdown|reboot|mkfs|diskpart|reg\s+delete)\b/i;
const safeTarget=(root:string,file:string)=>{const base=safeRoot(root),target=path.resolve(base,file||"");return target===base||target.startsWith(base+path.sep)?target:null};

export async function inspectProject(root:string):Promise<DevResult>{try{const cwd=safeRoot(root);const entries=await fs.readdir(cwd,{withFileTypes:true});const files=entries.filter(e=>e.isFile()).map(e=>e.name);const dirs=entries.filter(e=>e.isDirectory()).map(e=>e.name);const markers=["package.json","tsconfig.json","vite.config.ts","vite.config.js","next.config.js","requirements.txt","pyproject.toml","Cargo.toml","go.mod","pom.xml","build.gradle","Dockerfile",".git"].filter(x=>entries.some(e=>e.name===x));return{success:true,data:{cwd,files,dirs,projectMarkers:markers}}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao inspecionar projeto"}}}
export async function readProjectFile(root:string,file:string):Promise<DevResult>{try{const target=safeTarget(root,file);if(!target)return{success:false,error:"CAMINHO_FORA_DO_PROJETO"};const stat=await fs.stat(target);if(!stat.isFile())return{success:false,error:"Não é arquivo"};if(stat.size>5*1024*1024)return{success:false,error:"Arquivo excede 5 MB"};return{success:true,data:{path:target,content:await fs.readFile(target,"utf8")}}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao ler arquivo"}}}
export async function runProjectCommand(root:string,command:string,timeoutMs=120000):Promise<DevResult>{if(!command.trim())return{success:false,error:"COMANDO_VAZIO"};if(blocked.test(command))return{success:false,error:"COMANDO_BLOQUEADO"};return runCommand(command,safeRoot(root),Math.min(Math.max(timeoutMs,1000),600000))}
export async function detectTestCommand(root:string):Promise<DevResult>{try{const cwd=safeRoot(root),pkgRaw=await fs.readFile(path.join(cwd,"package.json"),"utf8"),pkg=JSON.parse(pkgRaw),scripts=pkg.scripts||{};const lock=(await Promise.all(["package-lock.json","pnpm-lock.yaml","yarn.lock","bun.lockb","bun.lock"].map(async f=>{try{await fs.access(path.join(cwd,f));return f}catch{return null}}))).filter(Boolean) as string[];const packageManager=lock.includes("pnpm-lock.yaml")?"pnpm":lock.includes("yarn.lock")?"yarn":lock.some(x=>x.startsWith("bun.lock"))?"bun":"npm";const run=(s:string)=>packageManager==="npm"?`npm run ${s}`:`${packageManager} ${s}`;const candidate=scripts.test?(packageManager==="npm"?"npm test":`${packageManager} test`):scripts["test:run"]?run("test:run"):scripts.typecheck?run("typecheck"):scripts.build?run("build"):null;return{success:true,data:{cwd,packageManager,lockfiles:lock,scripts:Object.keys(scripts),recommendedCommand:candidate}}}catch{return{success:true,data:{recommendedCommand:null}}}}
export async function writeProjectFile(root:string,file:string,content:string):Promise<DevResult>{try{const target=safeTarget(root,file);if(!target)return{success:false,error:"CAMINHO_FORA_DO_PROJETO"};await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,content,"utf8");return{success:true,data:{path:target,bytes:Buffer.byteLength(content,"utf8")}}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao escrever projeto"}}}
export async function createProjectWorkspace(root:string,name:string,packageManager="npm"):Promise<DevResult>{try{const base=safeRoot(root),target=safeTarget(base,name);if(!target||target===base)return{success:false,error:"CAMINHO_DE_PROJETO_INVALIDO"};try{await fs.access(target);return{success:false,error:"PROJETO_JA_EXISTE"}}catch{}await fs.mkdir(target,{recursive:true});await fs.writeFile(path.join(target,"README.md"),`# ${path.basename(target)}\n\nWorkspace criado pela A.R.I.S.\n`,"utf8");if(["npm","pnpm","yarn","bun"].includes(packageManager)){const pkg={name:path.basename(target).toLowerCase().replace(/[^a-z0-9-_]/g,"-"),version:"0.1.0",private:true};await fs.writeFile(path.join(target,"package.json"),JSON.stringify(pkg,null,2)+"\n","utf8")}return{success:true,data:{path:target,name:path.basename(target),packageManager,files:["README.md","package.json"]}}}catch(e){return{success:false,error:e instanceof Error?e.message:"Erro ao criar workspace"}}}
