import"dotenv/config";import express from"express";import cors from"cors";import{ask}from"./ai";import{remember,recall,clearMemory}from"./memory";import{runTools}from"./tools";
const app=express();const hits=new Map<string,{count:number;reset:number}>();const WINDOW=60000;const LIMIT=30;
app.use(cors({origin:process.env.CORS_ORIGIN||true}));app.use(express.json({limit:"1mb"}));
app.use((req,res,next)=>{if(req.path==="/api/health"){next();return}const key=req.ip||"unknown";const now=Date.now();const h=hits.get(key);if(!h||now>h.reset){hits.set(key,{count:1,reset:now+WINDOW});next();return}if(h.count>=LIMIT){res.status(429).json({error:"Limite temporário de requisições atingido. Tente novamente em instantes."});return}h.count++;next()});
app.get("/api/health",(_,r)=>r.json({ok:true,name:"A.R.I.S.",version:"2.1.0",capabilities:["chat","web","calculator","session-memory","orchestration"]}));
app.get("/api/memory/:sessionId",(req,res)=>res.json({memory:recall(req.params.sessionId).map(x=>x.content)}));
app.delete("/api/memory/:sessionId",(req,res)=>{clearMemory(req.params.sessionId);res.json({ok:true})});
app.post("/api/chat",async(req,res)=>{try{const{message,history=[],web=true,sessionId="default"}=req.body;if(typeof message!=="string"||!message.trim())return res.status(400).json({error:"message é obrigatório"});const id=String(sessionId).slice(0,100).replace(/[^a-zA-Z0-9_-]/g,"")||"default";const tool=web?await runTools(message):null;const sources=tool?.tool==="web_search"?tool.sources||[]:[];const answer=await ask(message,Array.isArray(history)?history:[],sources,id,tool?.tool==="calculator"?tool:null);remember(id,"Usuário: "+message);remember(id,"A.R.I.S.: "+answer);res.json({answer,sources,tool:tool?.tool||null,sessionId:id})}catch(e){res.status(500).json({error:e instanceof Error?e.message:"erro interno"})}});
app.listen(Number(process.env.PORT||8787),()=>console.log("A.R.I.S. online"));
