export type ModelRole="analise"|"critica"|"verificacao"|"alternativa"|"sintese";
export type ModelConfig={id:string;model:string;baseUrl:string;apiKey:string;roles:ModelRole[];timeoutMs:number;enabled:boolean;weight:number};
export type ModelRun={id:string;model:string;roles:ModelRole[];success:boolean;content?:string;error?:string;durationMs:number};
export type OrchestrationResult={runs:ModelRun[];successful:ModelRun[];failed:ModelRun[];durationMs:number};
type Msg={role:"user"|"assistant"|"system";content:string};
const split=(v:string|undefined)=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean);
function legacyModel():ModelConfig[]{const key=process.env.AI_API_KEY;if(!key)return[];return[{id:"principal",model:process.env.AI_MODEL||"gpt-4o-mini",baseUrl:(process.env.AI_BASE_URL||"https://api.openai.com/v1").replace(/\/$/,""),apiKey:key,roles:["analise","critica","verificacao","alternativa","sintese"],timeoutMs:Number(process.env.AI_MODEL_TIMEOUT_MS||15000),enabled:true,weight:1}]}
export function configuredModels():ModelConfig[]{const raw=process.env.ARIS_MODELS;if(!raw)return legacyModel();const ids=split(raw),models:ModelConfig[]=[];for(const id of ids){const p=`ARIS_MODEL_${id.toUpperCase().replace(/[^A-Z0-9]/g,"_")}_`;const apiKey=process.env[p+"API_KEY"]||"",model=process.env[p+"MODEL"]||"",baseUrl=(process.env[p+"BASE_URL"]||"").replace(/\/$/,"");if(!apiKey||!model||!baseUrl)continue;const roles=(split(process.env[p+"ROLES"]) as ModelRole[]).filter(r=>["analise","critica","verificacao","alternativa","sintese"].includes(r));models.push({id,model,baseUrl,apiKey,roles:roles.length?roles:["analise","critica","verificacao","alternativa"],timeoutMs:Number(process.env[p+"TIMEOUT_MS"]||process.env.AI_MODEL_TIMEOUT_MS||15000),enabled:process.env[p+"ENABLED"]!=="false",weight:Number(process.env[p+"WEIGHT"]||1)})}return models.filter(m=>m.enabled)}
function complexity(message:string){let score=1;if(message.length>300)score++;if(message.length>900)score++;if(/\b(analis|pesquis|compare|planej|arquitet|código|codigo|debug|implemente|projeto|estratég|estrateg)\b/i.test(message))score++;return Math.min(4,score)}
export function workBudget(message:string){const level=complexity(message);return{level,maxOutputTokens:[0,450,800,1400,2200][level],timeoutMultiplier:[0,.7,1,1.25,1.5][level]}}
async function request(model:ModelConfig,system:string,messages:Msg[],maxTokens:number):Promise<string>{const controller=new AbortController(),budget=workBudget(messages.at(-1)?.content||"");const timeout=Math.max(2000,Math.round(model.timeoutMs*budget.timeoutMultiplier)),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(model.baseUrl+"/chat/completions",{method:"POST",signal:controller.signal,headers:{Authorization:`Bearer ${model.apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:model.model,messages:[{role:"system",content:system},...messages],temperature:Number(process.env.AI_TEMPERATURE||.35),max_tokens:maxTokens})});if(!r.ok)throw new Error(`PROVIDER_${r.status}`);const j:any=await r.json();return j.choices?.[0]?.message?.content||""}finally{clearTimeout(timer)}}
export async function orchestrate(system:string,messages:Msg[],role:ModelRole|"all"="all"):Promise<OrchestrationResult>{const started=Date.now(),models=configuredModels().filter(m=>role==="all"||m.roles.includes(role));if(!models.length)return{runs:[],successful:[],failed:[],durationMs:0};const budget=workBudget(messages.at(-1)?.content||"");const runs=await Promise.all(models.map(async m=>{const t=Date.now();try{return{id:m.id,model:m.model,roles:m.roles,success:true,content:await request(m,system,messages,budget.maxOutputTokens),durationMs:Date.now()-t} as ModelRun}catch(e){return{id:m.id,model:m.model,roles:m.roles,success:false,error:e instanceof Error?e.message:"MODEL_ERROR",durationMs:Date.now()-t} as ModelRun}}));return{runs,successful:runs.filter(r=>r.success),failed:runs.filter(r=>!r.success),durationMs:Date.now()-started}}
export async function callBestAvailable(system:string,messages:Msg[],role:ModelRole="sintese"){const result=await orchestrate(system,messages,role);const best=result.successful.sort((a,b)=>{const ma=configuredModels().find(m=>m.id===a.id)?.weight||1,mb=configuredModels().find(m=>m.id===b.id)?.weight||1;return mb-ma})[0];if(best?.content)return best.content;throw new Error(result.failed[0]?.error||"Nenhum modelo disponível")}
