import fs from "node:fs/promises";
import path from "node:path";
import { callModel } from "./ai";
import { remember } from "./memory";

export type MemoryKind = "fact" | "preference" | "project" | "task" | "context";
export type SmartMemory = { id:string; kind:MemoryKind; content:string; confidence:number; createdAt:number; updatedAt:number; hits:number };
const DIR=path.resolve(process.env.DATA_DIR||"data"), FILE=path.join(DIR,"smart-memory.json"), MAX=300;
let store:Record<string,SmartMemory[]>|null=null, loading:Promise<void>|null=null;
async function ensure(){if(store)return;if(!loading)loading=(async()=>{try{store=JSON.parse(await fs.readFile(FILE,"utf8"))}catch{store={}}})();await loading}
async function persist(){await ensure();await fs.mkdir(DIR,{recursive:true});await fs.writeFile(FILE,JSON.stringify(store,null,2),"utf8")}
function important(t:string){return /\b(meu|minha|meus|minhas|eu sou|eu tenho|eu prefiro|gosto|não gosto|quero|preciso|projeto|empresa|trabalho|lembre|lembrar|sempre|nunca)\b/i.test(t)}
export async function extractSmartMemory(sessionId:string,userMessage:string){if(!important(userMessage)||!process.env.AI_API_KEY)return;try{const raw=await callModel(`Você é a memória da A.R.I.S. Extraia apenas informações estáveis e úteis para o futuro. Ignore perguntas triviais e não armazene senhas, chaves, dados financeiros, informações médicas, dados de autenticação ou outros segredos. Responda SOMENTE JSON array: [{"kind":"fact|preference|project|task|context","content":"...","confidence":0..1}]. Se nada for útil, [].`,[{role:"user",content:userMessage}]);const parsed=JSON.parse(raw.replace(/^```json\s*|\s*```$/g,""));if(!Array.isArray(parsed))return;await ensure();const list=store![sessionId]||[];for(const item of parsed.slice(0,5)){if(!item?.content||!["fact","preference","project","task","context"].includes(item.kind))continue;const content=String(item.content).trim().slice(0,2000);const existing=list.find(x=>x.content.toLowerCase()===content.toLowerCase());if(existing){existing.confidence=Math.max(existing.confidence,Math.min(1,Number(item.confidence)||.5));existing.updatedAt=Date.now();existing.hits++;continue}list.push({id:crypto.randomUUID(),kind:item.kind,content,confidence:Math.max(0,Math.min(1,Number(item.confidence)||.5)),createdAt:Date.now(),updatedAt:Date.now(),hits:1})}store![sessionId]=list.slice(-MAX);await persist();await remember(sessionId,"Memória inteligente atualizada: "+list.slice(-5).map(x=>`[${x.kind}] ${x.content}`).join(" | "))}catch{} }
export async function smartRecall(sessionId:string,query:string){await ensure();const list=store![sessionId]||[];const terms=query.toLowerCase().split(/\W+/).filter(x=>x.length>2);const ranked=list.map(x=>{const text=x.content.toLowerCase();const score=terms.reduce((n,t)=>n+(text.includes(t)?1:0),0)+x.confidence*.25;return{x,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||b.x.updatedAt-a.x.updatedAt).slice(0,12);for(const r of ranked)r.x.hits++;if(ranked.length)await persist();return ranked.map(r=>r.x)}
export async function smartMemoryContext(sessionId:string,query?:string){const list=query?await smartRecall(sessionId,query):((await ensure(),store![sessionId]||[]).slice(-12));return list.length?"\n\nMEMÓRIA INTELIGENTE RELEVANTE:\n"+list.map(x=>`- [${x.kind}] ${x.content}`).join("\n"):""}
export async function clearSmartMemory(sessionId:string){await ensure();delete store![sessionId];await persist()}
