import { browserNavigate,browserExtract,browserTask } from "./browser-task-agent";
import { executeVisualLoop } from "./desktop-vision-executor";
import { gitStatus,gitDiff,gitAddCommit } from "./github-agent";
import { inspectRepository } from "./github-capabilities";
import { addMemory } from "./task-memory";
import { recoverTask } from "./task-recovery";
import { requestConfirmation,consumeConfirmation } from "./confirmation-broker";
export type TaskStep={id:string;agent:"browser"|"desktop"|"development"|"github";action:string;input?:any;requiresConfirmation?:boolean;confirmationId?:string};
export type TaskPlan={goal:string;steps:TaskStep[]};
export type TaskRun={success:boolean;goal:string;history:any[];failedStep?:string;error?:string};
const handlers:any={browser:{navigate:async(x:any)=>browserNavigate(x.id||"default",x.url),extract:async(x:any)=>browserExtract(x.id||"default",x.selector),task:async(x:any)=>browserTask(x.id||"default",x.steps||[])},desktop:{visual_loop:async(x:any)=>executeVisualLoop(x.goal,Math.min(3,Number(x.maxIterations)||3))},github:{status:async(x:any)=>gitStatus(x.cwd),diff:async(x:any)=>gitDiff(x.cwd,!!x.staged),inspect_repository:async(x:any)=>inspectRepository(x.owner,x.repo),commit:async(x:any)=>gitAddCommit(x.cwd,x.message)},development:{noop:async()=>({success:true,data:{message:"Development action delegated to development agent"}})}};
async function brokerConfirm(step:TaskStep,taskId:string){if(step.confirmationId){const consumed=consumeConfirmation(step.confirmationId);return consumed.success}const request=requestConfirmation(taskId,step.id,`${step.agent}.${step.action}`,`A A.R.I.S. solicita autorização para executar uma ação modificadora: ${step.agent}.${step.action}`);addMemory(taskId,"decision",`Confirmation requested: ${request.id}`,"confirmation-broker",{step:step.id,action:request.action});return false}
export async function runTaskPlan(plan:TaskPlan,confirm?: (step:TaskStep)=>Promise<boolean>,taskId=`task-${Date.now()}`,allowRecovery=false):Promise<TaskRun>{const history:any[]=[];addMemory(taskId,"decision",`Started task: ${plan.goal}`,"orchestrator");for(const step of plan.steps){addMemory(taskId,"decision",`Starting ${step.id}: ${step.agent}.${step.action}`,"orchestrator",{input:step.input});if(!handlers[step.agent]?.[step.action]){const e=`UNSUPPORTED_STEP:${step.agent}.${step.action}`;addMemory(taskId,"error",e,"orchestrator");return{success:false,goal:plan.goal,history,error:e,failedStep:step.id}}if(step.requiresConfirmation){const approved=confirm?await confirm(step):await brokerConfirm(step,taskId);if(!approved){const e="CONFIRMATION_REQUIRED";addMemory(taskId,"error",e,"orchestrator",{step:step.id});return{success:false,goal:plan.goal,history,error:e,failedStep:step.id}}}try{const result=await handlers[step.agent][step.action](step.input||{});history.push({step:step.id,agent:step.agent,action:step.action,result});addMemory(taskId,result?.success===false?"error":"result",JSON.stringify(result).slice(0,20000),step.agent,{step:step.id});if(result&&!result.success){const failed={success:false,goal:plan.goal,history,error:result.error||"STEP_FAILED",failedStep:step.id};if(allowRecovery){const recovery=await recoverTask(plan.goal,plan,failed,2,taskId);history.push({type:"automatic-recovery",recovery});if(recovery.success)return{success:true,goal:plan.goal,history};}return failed}}catch(e){const msg=e instanceof Error?e.message:"STEP_EXCEPTION";addMemory(taskId,"error",msg,step.agent,{step:step.id});const failed={success:false,goal:plan.goal,history,error:msg,failedStep:step.id};if(allowRecovery){const recovery=await recoverTask(plan.goal,plan,failed,2,taskId);history.push({type:"automatic-recovery",recovery});if(recovery.success)return{success:true,goal:plan.goal,history}}return failed}}addMemory(taskId,"result",`Completed task: ${plan.goal}`,"orchestrator");return{success:true,goal:plan.goal,history}}
