import crypto from "node:crypto";import fs from "node:fs";import path from "node:path";import { getTool,ToolRisk } from "./tool-engine";
export type ConfirmationRequest={id:string;sessionId:string;taskId?:string;projectId?:string;tool:string;query:string;risk:ToolRisk;message:string;createdAt:number;expiresAt:number;status:"pending"|"approved"|"rejected"|"expired"};
type ConfirmationStore={pending:ConfirmationRequest[];approved:[string,number][]};
const dir=path.resolve(process.env.DATA_DIR||"data"),file=path.join(dir,"confirmations.json");const pending=new Map<string,ConfirmationRequest>();const approved=new Map<string,number>();const TTL=Number(process.env.TOOL_CONFIRMATION_TTL_MS)||120000;let loaded=false;
function load(){if(loaded)return;loaded=true;try{const raw=JSON.parse(fs.readFileSync(file,"utf8")) as ConfirmationStore;for(const x of raw.pending||[])pending.set(x.id,x);for(const [k,v] of raw.approved||[])approved.set(k,v)}catch{}}
function save(){fs.mkdirSync(dir,{recursive:true});const tmp=`${file}.tmp`;const data:ConfirmationStore={pending:[...pending.values()],approved:[...approved.entries()]};fs.writeFileSync(tmp,JSON.stringify(data,null,2),"utf8");fs.renameSync(tmp,file)}
function cleanup(){load();const now=Date.now();let changed=false;for(const [id,x] of pending)if(x.status==="pending"&&x.expiresAt<=now){x.status="expired";pending.set(id,x);changed=true}for(const [key,expires] of approved)if(expires<=now){approved.delete(key);changed=true}if(changed)save()}
const key=(sessionId:string,tool:string,query:string)=>`${sessionId}\u0000${tool}\u0000${query}`;
export function createConfirmation(sessionId:string,tool:string,query:string,projectId?:string,taskId?:string){cleanup();const def=getTool(tool);if(!def)throw new Error("Ferramenta não encontrada.");const id=crypto.randomUUID(),risk=def.risk||"low",expiresAt=Date.now()+TTL,x:ConfirmationRequest={id,sessionId,taskId,projectId,tool,query,risk,message:`A A.R.I.S. precisa da sua confirmação para executar “${def.description}”. Risco: ${risk}.`,createdAt:Date.now(),expiresAt,status:"pending"};pending.set(id,x);save();return x}
export function getConfirmation(id:string){cleanup();return pending.get(id)}
export function listConfirmations(sessionId:string){cleanup();return [...pending.values()].filter(x=>x.sessionId===sessionId&&x.status==="pending")}
export function resolveConfirmation(id:string,approvedDecision:boolean){cleanup();const x=pending.get(id);if(!x)throw new Error("Solicitação não encontrada ou expirada.");if(x.status!=="pending")throw new Error("Solicitação já resolvida.");x.status=approvedDecision?"approved":"rejected";pending.set(id,x);if(approvedDecision)approved.set(key(x.sessionId,x.tool,x.query),x.expiresAt);save();return x}
export function consumeApprovedExecution(sessionId:string,tool:string,query:string){cleanup();const k=key(sessionId,tool,query);if(!approved.has(k))return false;approved.delete(k);save();return true}
export function clearConfirmation(id:string){load();pending.delete(id);save();return{success:true,id}}
