import { useRef, useState } from "react";
type M={role:"user"|"assistant";content:string};
const newId=()=>crypto.randomUUID();
const getSession=()=>localStorage.getItem("aris-session")||(()=>{const id=newId();localStorage.setItem("aris-session",id);return id})();
const API=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
export default function App(){
 const[sessionId,setSessionId]=useState(getSession),[text,setText]=useState(""),[busy,setBusy]=useState(false),[msgs,setMsgs]=useState<M[]>([{role:"assistant",content:"A.R.I.S. online. Centro de operações pronto. Em que posso ser útil?"}]),[docs,setDocs]=useState<string[]>([]),file=useRef<HTMLInputElement>(null);
 async function refreshDocs(id=sessionId){try{const r=await fetch(`${API}/api/documents/${id}`);const j=await r.json();setDocs((j.documents||[]).map((d:any)=>d.name||"documento"));}catch{}}
 async function newSession(){const id=newId();localStorage.setItem("aris-session",id);setSessionId(id);setMsgs([{role:"assistant",content:"Nova sessão iniciada. Memória independente criada. Estou à sua disposição."}]);setDocs([]);}
 async function send(){if(!text.trim()||busy)return;const q=text.trim();setText("");const history=msgs;setMsgs(m=>[...m,{role:"user",content:q}]);setBusy(true);try{const r=await fetch(`${API}/api/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:q,history,web:true,sessionId})});const j=await r.json();setMsgs(m=>[...m,{role:"assistant",content:j.answer||j.error||"Não foi possível obter uma resposta."}])}catch{setMsgs(m=>[...m,{role:"assistant",content:"Não consegui concluir a operação. O servidor parece ter decidido tirar uma pequena pausa sem autorização."}])}finally{setBusy(false)}}
 async function clear(){await fetch(`${API}/api/memory/${sessionId}`,{method:"DELETE"});setMsgs([{role:"assistant",content:"Memória e documentos da sessão eliminados. Uma pequena faxina mental, senhor."}]);setDocs([])}
 async function upload(){const f=file.current?.files?.[0];if(!f)return;const allowed=["txt","md","csv","json","html"];const ext=f.name.split(".").pop()?.toLowerCase();if(!ext||!allowed.includes(ext)){setMsgs(m=>[...m,{role:"assistant",content:"Formato não suportado. Atualmente aceito TXT, MD, CSV, JSON e HTML."}]);return}const content=await f.text();if(content.length>40000){setMsgs(m=>[...m,{role:"assistant",content:"Esse documento excede o limite de 40.000 caracteres. Uma quantidade admirável de leitura, mas desnecessária para uma única operação."}]);return}const r=await fetch(`${API}/api/documents/${sessionId}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.name,content})});setMsgs(m=>[...m,{role:"assistant",content:r.ok?`Documento ${f.name} incorporado à sessão.`:"Não consegui incorporar o documento."}]);if(file.current)file.current.value="";refreshDocs()}
 return <div className="app"><aside><h2>◈ A.R.I.S.</h2><small>ASSISTENTE • CENTRO DE OPERAÇÕES</small><button onClick={newSession}>＋ Nova sessão</button><button onClick={clear}>⌫ Limpar memória</button><button onClick={()=>file.current?.click()}>⇧ Adicionar documento</button><input ref={file} type="file" accept=".txt,.md,.csv,.json,.html" hidden onChange={upload}/><div className="capabilities"><b>CAPACIDADES</b><span>● Web</span><span>● Raciocínio</span><span>● Memória persistente</span><span>● Documentos</span><span>● Calculadora</span><span>● Relógio</span></div>{docs.length>0&&<div className="documents"><b>DOCUMENTOS DA SESSÃO</b>{docs.map((d,i)=><span key={i}>▸ {d}</span>)}</div>}</aside><main><header><div><small>ADVANCED INTELLIGENCE CORE • v2.5</small><h1>A.R.I.S.</h1></div><span>● ONLINE</span></header><section>{msgs.map((m,i)=><article className={m.role} key={i}><b>{m.role==="user"?"VOCÊ":"A.R.I.S."}</b><p>{m.content}</p></article>)}{busy&&<i>A.R.I.S. processando, verificando e consultando ferramentas…</i>}</section><footer><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Dê uma ordem ou faça uma pergunta…"/><button onClick={send} disabled={busy}>{busy?"PROCESSANDO…":"ENVIAR ↗"}</button></footer></main></div>
}